ai:
  base_url: "https://api.openai.com/v1"
  api_key: "your-api-key"
  timeout: 30s
  max_retries: 3
  use_proxy: false
  proxy_address: ""

lottery_api:
  base_url: "https://api.jisuapi.com/caipiao/query"
  app_key: "your-api-key"

database:
  path: "data/lottery.db"

server:
  port: 8080
  admin_key: "your-admin-key"

jwt:
  secret: "your-jwt-secret"
  expiration: 86400 # 24小时

scheduler:
  result_fetch_cron: "0 30 21,22,23 * * *" # 每天21:30,22:30,23:30爬取开奖结果

# 阿里云OSS配置
aliyun_oss:
  endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
  access_key_id: "your-access-key-id"
  access_key_secret: "your-access-key-secret"
  bucket_name: "your-bucket-name"
  bucket_domain: "https://your-bucket-name.oss-cn-hangzhou.aliyuncs.com"

# 初始用户配置
users:
  - username: "admin"
    password: "admin123"

# 彩票类型配置
lottery_types:
  - code: "fc_ssq"
    name: "双色球"
    schedule_cron: "0 0 20 * * 2,4,0" # 每周二、四、日20:00
    model_name: "gpt-3.5-turbo"
    is_active: true
    caipiao_id: 101 # 极速API的双色球ID

  - code: "tc_dlt"
    name: "大乐透"
    schedule_cron: "0 0 20 * * 1,3,6" # 每周一、三、六20:00
    model_name: "gpt-3.5-turbo"
    is_active: true
    caipiao_id: 102 # 极速API的大乐透ID
