ai:
  base_url: "https://openrouter.ai/api/v1"  # 需要替换为实际的OneAPI地址
  api_key: "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"  # 需要填写实际的API密钥
  timeout: 30s
  max_retries: 3
  use_proxy: true      # 是否启用代理
  proxy_address: "http://127.0.0.1:8888"  # Fiddler 代理地址

database:
  path: "./data/lottery.db"

server:
  port: 3000

jwt:
  secret: "your-jwt-secret-key"  # 生产环境应使用环境变量
  expiration: 86400  # token有效期24小时（秒）

# 初始化用户配置
users:
  - username: "admin"
    password: "123456"

# 初始化彩票类型配置
lottery_types:
  - name: "双色球"
    schedule_cron: "0 0 20 * 2,4,0" # 每周二、四、日20:00
    model_name: "deepseek/deepseek-r1:free"
    is_active: true
  - name: "大乐透"
    schedule_cron: "0 0 20 * 1,3,6" # 每周一、三、六20:00
    model_name: "deepseek/deepseek-r1:free"
    is_active: true
