ai:
  base_url: "https://openrouter.ai/api/v1"  # 需要替换为实际的OneAPI地址
  api_key: "111111"  # 需要填写实际的API密钥
  timeout: 30s
  max_retries: 3
  use_proxy: false      # 是否启用代理
  proxy_address: "http://127.0.0.1:8888"  # Fiddler 代理地址

# 彩票API配置
lottery_api:
  base_url: "https://api.jisuapi.com/caipiao/query"
  app_key: "111111"  # 请替换为实际的API Key

database:
  path: "./data/lottery.db"

server:
  port: 3001

jwt:
  secret: "your-jwt-secret-key"  # 生产环境应使用环境变量
  expiration: 86400  # token有效期24小时（秒）

# 初始化用户配置
users:
  - username: "admin"
    password: "123456"

# 任务调度配置
scheduler:
  result_fetch_cron: "0 22 * * *"  # 每天21:00爬取开奖结果

# 初始化彩票类型配置
lottery_types:
  - code: "fc_ssq"     # 福彩双色球
    name: "双色球"
    schedule_cron: "0 0 0 * 2,4,5" # 每周二、四、日20:00
    model_name: "deepseek/deepseek-chat:free"
    is_active: true
    caipiao_id: 11   # 极速API的彩票ID
  - code: "tc_dlt"     # 体彩大乐透
    name: "大乐透"
    schedule_cron: "0 0 0 * 1,3,5" # 每周一、三、六20:00
    model_name: "deepseek/deepseek-chat:free"
    is_active: true
    caipiao_id: 14   # 极速API的彩票ID
