root = "."
tmp_dir = "bin/.air"

[build]
cmd = "go build -o ./bin/lottery-dev.exe ./cmd"
bin = "bin/lottery-dev.exe"
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["bin/.air", "data", "log", ".history"]
delay = 500
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true

[misc]
clean_on_exit = true
