// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.LoginResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前登录用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.UserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "创建账号并返回用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.AuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.UserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_auth.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回系统当前已加载并入库的彩票类型",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取已启用彩票列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.LotteryListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/draws/sync-history": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "批量调用历史开奖同步，lotteryCodes 为空时同步所有已启用彩票",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "批量同步多种彩票历史开奖",
                "parameters": [
                    {
                        "description": "批量历史同步参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.SyncDrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.BatchSyncResultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/tickets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回最近录入的全部票据记录，适合在不预先区分彩种的记录页使用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取全部票据列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "返回数量，默认 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "基于上传记录和识别结果确认票据入库，彩种由识别结果或推荐记录自动决定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "通用票据入库并判奖",
                "parameters": [
                    {
                        "description": "入库参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.CreateTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketDetailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/tickets/recognize": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "基于已上传原图执行 OCR 识别，并自动判断彩票类型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "识别通用彩票内容",
                "parameters": [
                    {
                        "description": "识别参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.RecognizeTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketRecognitionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/tickets/upload-image": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传时不要求先知道彩票类型，图片会在识别阶段自动判断彩种",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "上传通用彩票原图",
                "parameters": [
                    {
                        "type": "file",
                        "description": "彩票图片",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/dashboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回指定彩票的最新开奖、最新推荐、最近票据和统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取彩票看板",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.DashboardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/draws/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用极速数据 query 接口同步当前期或指定期的开奖信息，并触发票据与推荐结算",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "同步当期开奖",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "同步参数，issue 为空时同步当前期",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.SyncDrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.SyncResultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/draws/sync-history": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用极速数据 history 接口分页同步指定彩票的历史开奖信息，默认最近 100 期",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "同步单种彩票历史开奖",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "历史同步参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.SyncDrawRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.SyncResultResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/recommendations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回指定彩票最近生成的推荐记录列表，包含是否已记录购买票据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取推荐列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回数量，默认 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.RecommendationListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/recommendations/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "按当前彩票配置的 AI 模型和提示词生成推荐号码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "生成推荐号码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "推荐生成参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.GenerateRecommendationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.RecommendationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/recommendations/latest": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回指定彩票最近一次生成的推荐号码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取最新推荐",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.RecommendationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/recommendations/{recommendationId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回指定推荐记录的完整号码、命中情况和购买关联信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取推荐详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "推荐记录 ID",
                        "name": "recommendationId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.RecommendationDetailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/tickets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回指定彩票最近录入的票据记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "获取票据列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq、dlt",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "返回数量，默认 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "基于上传记录和识别结果确认票据入库，并在已开奖时自动判奖",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "确认入库并判奖",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "入库参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.CreateTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketDetailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/tickets/recognize": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "基于已上传原图执行 OCR 识别，只返回识别结果，不入库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "识别彩票内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "识别参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.RecognizeTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketRecognitionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/tickets/scan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "上传票据图片并识别号码，识别成功后自动入库并尝试判奖",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "扫描彩票票据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "彩票图片",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "期号",
                        "name": "issue",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "购买时间，RFC3339 格式",
                        "name": "purchasedAt",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "OCR 降级文本",
                        "name": "ocrText",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "备注",
                        "name": "notes",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lotteries/{code}/tickets/upload-image": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "仅上传并保存彩票原图，不执行 OCR 和入库",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lottery"
                ],
                "summary": "上传彩票原图",
                "parameters": [
                    {
                        "type": "string",
                        "description": "彩票编码，如 ssq",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "彩票图片",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.TicketUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_lottery.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-fiber-starter_internal_model_lottery.DrawPrize": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "drawResultId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "prizeName": {
                    "type": "string"
                },
                "prizeRule": {
                    "type": "string"
                },
                "singleBonus": {
                    "type": "number"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                },
                "winnerCount": {
                    "type": "integer"
                }
            }
        },
        "go-fiber-starter_internal_model_lottery.DrawResult": {
            "type": "object",
            "properties": {
                "blueNumbers": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "drawDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issue": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "prizeDetails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.DrawPrize"
                    }
                },
                "prizePoolAmount": {
                    "type": "number"
                },
                "rawPayload": {
                    "type": "string"
                },
                "redNumbers": {
                    "type": "string"
                },
                "saleAmount": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                }
            }
        },
        "go-fiber-starter_internal_model_lottery.LotteryType": {
            "type": "object",
            "properties": {
                "blueCount": {
                    "type": "integer"
                },
                "blueMax": {
                    "type": "integer"
                },
                "blueMin": {
                    "type": "integer"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "recommendationCount": {
                    "type": "integer"
                },
                "recommendationModel": {
                    "type": "string"
                },
                "recommendationProvider": {
                    "type": "string"
                },
                "redCount": {
                    "type": "integer"
                },
                "redMax": {
                    "type": "integer"
                },
                "redMin": {
                    "type": "integer"
                },
                "remoteLotteryId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                },
                "visionModel": {
                    "type": "string"
                },
                "visionProvider": {
                    "type": "string"
                }
            }
        },
        "go-fiber-starter_internal_model_lottery.Recommendation": {
            "type": "object",
            "properties": {
                "basis": {
                    "type": "string"
                },
                "checkedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.RecommendationEntry"
                    }
                },
                "id": {
                    "type": "string"
                },
                "issue": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prizeAmount": {
                    "type": "number"
                },
                "promptVersion": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "rawPayload": {
                    "type": "string"
                },
                "strategy": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                }
            }
        },
        "go-fiber-starter_internal_model_lottery.RecommendationEntry": {
            "type": "object",
            "properties": {
                "blueNumbers": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isWinning": {
                    "type": "boolean"
                },
                "matchSummary": {
                    "type": "string"
                },
                "prizeAmount": {
                    "type": "number"
                },
                "prizeName": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "recommendationId": {
                    "type": "string"
                },
                "redNumbers": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                }
            }
        },
        "go-fiber-starter_internal_model_lottery.TicketEntry": {
            "type": "object",
            "properties": {
                "blueNumbers": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isWinning": {
                    "type": "boolean"
                },
                "matchSummary": {
                    "type": "string"
                },
                "multiple": {
                    "type": "integer"
                },
                "prizeAmount": {
                    "type": "number"
                },
                "prizeName": {
                    "type": "string"
                },
                "redNumbers": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "ticketId": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.BatchSyncResult": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.SyncResult"
                    }
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.DashboardData": {
            "type": "object",
            "properties": {
                "latestDraw": {
                    "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.DrawResult"
                },
                "latestRecommendation": {
                    "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.Recommendation"
                },
                "lottery": {
                    "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.LotteryType"
                },
                "recentTickets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketDetail"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.DashboardStats"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.DashboardStats": {
            "type": "object",
            "properties": {
                "totalCost": {
                    "type": "number"
                },
                "totalPrize": {
                    "type": "number"
                },
                "totalTickets": {
                    "type": "integer"
                },
                "wonTickets": {
                    "type": "integer"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.ParsedEntry": {
            "type": "object",
            "properties": {
                "blue": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "multiple": {
                    "type": "integer"
                },
                "red": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.RecommendationDetail": {
            "type": "object",
            "properties": {
                "basis": {
                    "type": "string"
                },
                "checkedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.RecommendationEntry"
                    }
                },
                "entryCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isPurchased": {
                    "type": "boolean"
                },
                "issue": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prizeAmount": {
                    "type": "number"
                },
                "promptVersion": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "purchasedTicket": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketDetail"
                },
                "rawPayload": {
                    "type": "string"
                },
                "strategy": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                },
                "winningCount": {
                    "type": "integer"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.SyncResult": {
            "type": "object",
            "properties": {
                "issue": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "syncedCount": {
                    "type": "integer"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.TicketDetail": {
            "type": "object",
            "properties": {
                "checkedAt": {
                    "type": "string"
                },
                "costAmount": {
                    "type": "number"
                },
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "drawDate": {
                    "type": "string"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.TicketEntry"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imagePath": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "issue": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "prizeAmount": {
                    "type": "number"
                },
                "purchasedAt": {
                    "type": "string"
                },
                "recognizedText": {
                    "type": "string"
                },
                "recommendationId": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.TicketRecognitionDraft": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.ParsedEntry"
                    }
                },
                "issue": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "rawText": {
                    "type": "string"
                },
                "upload": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketUploadDetail"
                }
            }
        },
        "go-fiber-starter_internal_service_lottery.TicketUploadDetail": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "指定为自动创建时间",
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imagePath": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "lotteryCode": {
                    "type": "string"
                },
                "originalFilename": {
                    "type": "string"
                },
                "recognitionConfidence": {
                    "type": "number"
                },
                "recognitionIssue": {
                    "type": "string"
                },
                "recognitionPayload": {
                    "type": "string"
                },
                "recognizedText": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "指定为自动更新时间",
                    "type": "string"
                }
            }
        },
        "internal_api_auth.AuthRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "pass123"
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "internal_api_auth.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "flag": {
                    "type": "boolean",
                    "example": false
                },
                "msg": {
                    "type": "string",
                    "example": "请求失败"
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_auth.LoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                }
            }
        },
        "internal_api_auth.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/internal_api_auth.LoginData"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_auth.UserData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "username": {
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "internal_api_auth.UserResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/internal_api_auth.UserData"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.BatchSyncResultResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.BatchSyncResult"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.CreateTicketEntryRequest": {
            "type": "object",
            "properties": {
                "blueNumbers": {
                    "type": "string"
                },
                "multiple": {
                    "type": "integer"
                },
                "redNumbers": {
                    "type": "string"
                }
            }
        },
        "internal_api_lottery.CreateTicketRequest": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_lottery.CreateTicketEntryRequest"
                    }
                },
                "issue": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "purchasedAt": {
                    "type": "string"
                },
                "recommendationId": {
                    "type": "string"
                },
                "uploadId": {
                    "type": "string"
                }
            }
        },
        "internal_api_lottery.DashboardResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.DashboardData"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "flag": {
                    "type": "boolean",
                    "example": false
                },
                "msg": {
                    "type": "string",
                    "example": "请求失败"
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.GenerateRecommendationRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "internal_api_lottery.LotteryListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.LotteryType"
                    }
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.RecognizeTicketRequest": {
            "type": "object",
            "properties": {
                "ocrText": {
                    "type": "string"
                },
                "uploadId": {
                    "type": "string"
                }
            }
        },
        "internal_api_lottery.RecommendationDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.RecommendationDetail"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.RecommendationListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.RecommendationDetail"
                    }
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.RecommendationResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_model_lottery.Recommendation"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.SyncDrawRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "issue": {
                    "type": "string"
                },
                "lotteryCodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "start": {
                    "type": "integer"
                }
            }
        },
        "internal_api_lottery.SyncResultResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.SyncResult"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.TicketDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketDetail"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.TicketListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketDetail"
                    }
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.TicketRecognitionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketRecognitionDraft"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        },
        "internal_api_lottery.TicketUploadResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "data": {
                    "$ref": "#/definitions/go-fiber-starter_internal_service_lottery.TicketUploadDetail"
                },
                "flag": {
                    "type": "boolean",
                    "example": true
                },
                "time": {
                    "type": "string",
                    "example": "2026-03-16T10:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:25610",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Go Fiber API",
	Description:      "Go Fiber Starter API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
