oneapi:
  base_url: "https://api.oneapi.com/v1"  # 需要替换为实际的OneAPI地址
  api_key: ""  # 需要填写实际的API密钥
  allowed_models:
    - "gpt-4"
    - "gpt-3.5-turbo"
    - "claude-2.1"
  timeout: 30s
  max_retries: 3

database:
  path: "./data/lottery.db"

server:
  port: 3000
  admin_key: "dev-admin-key"  # 仅用于开发环境，生产环境需要更改为安全的密钥
